term.clear()
print('Welcome and God bless to LoveCreate! here you can create your own LoveOS App')
read()
term.clear()
print('App name with love?')
local appname = read()
print('We will open you the editor to customize your app with love!')
read()
shell.run("edit /apps/" .. appname)
print('Your app of love is done! God bless you!')
read()
term.clear()
