term.clear()
print('Welcome and God bless to LoveOS Uninstaller!')
print()
print('WARNING: Are you sure to uninstall LoveOS? All data will be lost! :C (Enter: Yes, Hold Ctrl+T: Cancel)')
read()
print('Uninstalling LoveOS..')
shell.run('rm /*')
print('Done! :C')
shell.run('reboot')
